trigger:
- master
- duplicate-test

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'lurodrig-sonarqube.ngrok.io'
    projectKey: 'unit-testing-using-dotnet-test'
    projectName: 'unit-testing-using-dotnet-test'
    extraProperties: | 
       sonar.verbose=true
       sonar.cs.vstest.reportsPaths=*.trx,**/*.trx,**/**/*.trx,$(Agent.TempDirectory)/*.trx,$(Agent.TempDirectory)**/*.trx 
       sonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml,**/*.xml    
  displayName: 'SonarQube Prepare'


- task: VSBuild@1
  inputs:
   solution: 'unit-testing-using-dotnet-test.sln'
   logFileVerbosity: 'detailed'
   vsVersion: 'latest'
   clean: true

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\*test*.dll
        !**\*Microsoft*.dll
        !**\*testcentric*.dll
        !**\*TestUtilities*.dll
        !**\TestableIO*.dll
        !**\*LeakTest*.dll
        !**\obj\**
    codeCoverageEnabled: true
    diagnosticsEnabled: true
    vsTestVersion: 'latest'
    otherConsoleOptions: '/collect:"Code Coverage;Format=XML"'

#- task: PublishCodeCoverageResults@2
#  inputs:
#    summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/*.xml'

- task: SonarQubeAnalyze@7