trigger:
- master

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -O -L https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_x64_windows_hotspot_19.0.2_7.zip
      ls -l
      pwd

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'lurodrig-sonarqube.ngrok.io'
    projectKey: 'unit-testing-using-dotnet-test'
    projectName: 'unit-testing-using-dotnet-test'
    extraProperties: 'sonar.verbose=true'
  displayName: 'SonarQube Prepare'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
   solution: 'unit-testing-using-dotnet-test.sln'
   logFileVerbosity: 'detailed'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\*test*.dll
        !**\*Microsoft*.dll
        !**\*testcentric*.dll
        !**\*TestUtilities*.dll
        !**\TestableIO*.dll
        !**\*LeakTest*.dll
        !**\obj\**
    searchFolder: 'PrimeService.Tests'
    codeCoverageEnabled: true
    diagnosticsEnabled: true

- task: SonarQubeAnalyze@6
