trigger:
- master

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:
- task: VSBuild@1
  inputs:
   solution: 'unit-testing-using-dotnet-test.sln'
   restoreNugetPackages: 'true'
   logFileVerbosity: 'detailed'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\*test*.dll
        !**\*Microsoft*.dll
        !**\*testcentric*.dll
        !**\*TestUtilities*.dll
        !**\TestableIO*.dll
        !**\*LeakTest*.dll
        !**\obj\**
    searchFolder: '$(Build.SourcesDirectory)\**.Tests'
    codeCoverageEnabled: 'true'
    diagnosticsEnabled: 'true'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'lurodrig-sonarqube.ngrok.io'
    scannerMode: 'MSBuild'
    projectKey: 'unit-testing-using-dotnet-test'
    projectName: 'unit-testing-using-dotnet-test'
    extraProperties: 'sonar.verbose=true'
    msBuildVersion: '6.2.0.85879'
  displayName: 'SonarQube Prepare'

- task: SonarQubeAnalyze@6
