trigger:
- master
- duplicate-test

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'lurodrig-sonarqube.ngrok.io'
    projectKey: 'unit-testing-using-dotnet-test'
    projectName: 'unit-testing-using-dotnet-test'
    extraProperties: | 
      sonar.verbose=true
      sonar.cs.vscoveragexml.reportsPaths="D:\a\_temp\TestResults\**\*.xml"
  displayName: 'SonarQube Prepare'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
   solution: 'unit-testing-using-dotnet-test.sln'
   logFileVerbosity: 'detailed'
   vsVersion: 'latest'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\*test*.dll
        !**\*Microsoft*.dll
        !**\*testcentric*.dll
        !**\*TestUtilities*.dll
        !**\TestableIO*.dll
        !**\*LeakTest*.dll
        !**\obj\**
    searchFolder: 'PrimeService.Tests'
    codeCoverageEnabled: true
    diagnosticsEnabled: true
    vsTestVersion: 'latest'
    otherConsoleOptions: '/collect:"Code Coverage;Format=XML"'

#- task: PublishCodeCoverageResults@2
#  inputs:
#    summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/*.xml'

- task: SonarQubeAnalyze@7